import type { Product } from "./types";

export const INDIAN_RETAIL_MASTER_CATALOG: Omit<Product, "id" | "stock" | "healthScore" | "status" | "lastRestocked" | "lastUpdated">[] = [
  {
    name: "Good Day Butter Cookies",
    sku: "SKU-GOODDAY-BUTTER-200G",
    barcode: "8901063012613",
    category: "Packaged Foods",
    brand: "Britannia",
    batch: "BATCH-24A",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "A1-02",
    minStock: 20,
    maxStock: 500,
    unit: "pcs",
    mfgDate: "2026-06-01",
    expiryDate: "2026-12-01",
    image: "",
    packageSize: "200g Pack",
    weight: "200g",
    manufacturer: "Britannia Industries Ltd",
    description: "Rich butter cookies with delightful crunchy texture.",
    source: "database",
  },
  {
    name: "Good Day Cashew Cookies",
    sku: "SKU-GOODDAY-CASHEW-100G",
    barcode: "8901063012620",
    category: "Packaged Foods",
    brand: "Britannia",
    batch: "BATCH-24B",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "A1-03",
    minStock: 20,
    maxStock: 500,
    unit: "pcs",
    mfgDate: "2026-06-01",
    expiryDate: "2026-12-01",
    image: "",
    packageSize: "100g Pack",
    weight: "100g",
    manufacturer: "Britannia Industries Ltd",
    description: "Crunchy cookies enriched with cashew nuts and butter.",
    source: "database",
  },
  {
    name: "Parle-G Original Gluco Biscuits",
    sku: "SKU-PARLEG-800G",
    barcode: "8901719101037",
    category: "Packaged Foods",
    brand: "Parle",
    batch: "BATCH-PG-1",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "A1-01",
    minStock: 30,
    maxStock: 1000,
    unit: "pcs",
    mfgDate: "2026-05-15",
    expiryDate: "2026-11-15",
    image: "",
    packageSize: "800g Family Pack",
    weight: "800g",
    manufacturer: "Parle Products Pvt Ltd",
    description: "India's beloved glucose biscuits made with milk and wheat.",
    source: "database",
  },
  {
    name: "Britannia Marie Gold Biscuits",
    sku: "SKU-MARIEGOLD-250G",
    barcode: "8901063011418",
    category: "Packaged Foods",
    brand: "Britannia",
    batch: "BATCH-MG-1",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse B — Pune",
    shelf: "A2-05",
    minStock: 25,
    maxStock: 600,
    unit: "pcs",
    mfgDate: "2026-06-10",
    expiryDate: "2026-12-10",
    image: "",
    packageSize: "250g Pack",
    weight: "250g",
    manufacturer: "Britannia Industries Ltd",
    description: "Crispy, light tea biscuits enriched with vitamins and minerals.",
    source: "database",
  },
  {
    name: "Britannia Bourbon Chocolate Cream Biscuits",
    sku: "SKU-BOURBON-150G",
    barcode: "8901063013214",
    category: "Packaged Foods",
    brand: "Britannia",
    batch: "BATCH-BB-1",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "A2-08",
    minStock: 20,
    maxStock: 400,
    unit: "pcs",
    mfgDate: "2026-05-20",
    expiryDate: "2026-11-20",
    image: "",
    packageSize: "150g Pack",
    weight: "150g",
    manufacturer: "Britannia Industries Ltd",
    description: "Rich dark chocolate cream sandwich biscuits sprinkled with sugar.",
    source: "database",
  },
  {
    name: "Sunfeast Dark Fantasy Choco Fills",
    sku: "SKU-DARKFANTASY-300G",
    barcode: "8901725114014",
    category: "Packaged Foods",
    brand: "Sunfeast",
    batch: "BATCH-DF-1",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse C — Chennai",
    shelf: "B1-02",
    minStock: 15,
    maxStock: 350,
    unit: "pcs",
    mfgDate: "2026-06-15",
    expiryDate: "2026-12-15",
    image: "",
    packageSize: "300g Box",
    weight: "300g",
    manufacturer: "ITC Ltd",
    description: "Crispy cookies with molten rich chocolate cream filling.",
    source: "database",
  },
  {
    name: "Oreo Original Vanilla Cream Sandwich Biscuits",
    sku: "SKU-OREO-VANILLA-120G",
    barcode: "7622201750018",
    category: "Packaged Foods",
    brand: "Cadbury",
    batch: "BATCH-OR-1",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse B — Pune",
    shelf: "B1-04",
    minStock: 20,
    maxStock: 450,
    unit: "pcs",
    mfgDate: "2026-05-01",
    expiryDate: "2026-11-01",
    image: "",
    packageSize: "120g Pack",
    weight: "120g",
    manufacturer: "Mondelez India Foods Ltd",
    description: "Classic chocolate cookies with sweet vanilla creme center.",
    source: "database",
  },
  {
    name: "Maggi 2-Minute Masala Instant Noodles",
    sku: "SKU-MAGGI-70G",
    barcode: "8901058852899",
    category: "Packaged Foods",
    brand: "Nestle",
    batch: "BATCH-MAGGI-70",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "C1-01",
    minStock: 50,
    maxStock: 1200,
    unit: "pcs",
    mfgDate: "2026-06-01",
    expiryDate: "2027-03-01",
    image: "",
    packageSize: "70g Single Pack",
    weight: "70g",
    manufacturer: "Nestle India Ltd",
    description: "Classic Indian favourite noodles with authentic spice mix.",
    source: "database",
  },
  {
    name: "Maggi 2-Minute Masala Noodles (4-Pack)",
    sku: "SKU-MAGGI-4PACK-280G",
    barcode: "8901058852905",
    category: "Packaged Foods",
    brand: "Nestle",
    batch: "BATCH-MAGGI-4P",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "C1-02",
    minStock: 30,
    maxStock: 800,
    unit: "pack",
    mfgDate: "2026-06-01",
    expiryDate: "2027-03-01",
    image: "",
    packageSize: "280g (4 x 70g)",
    weight: "280g",
    manufacturer: "Nestle India Ltd",
    description: "4-pack bundle of 2-Minute Masala noodles with Tastemaker.",
    source: "database",
  },
  {
    name: "Lay's India's Magic Masala Potato Chips",
    sku: "SKU-LAYS-MASALA-50G",
    barcode: "8901491101838",
    category: "Packaged Foods",
    brand: "Lay's",
    batch: "BATCH-LAYS-M",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse B — Pune",
    shelf: "C2-01",
    minStock: 25,
    maxStock: 500,
    unit: "pcs",
    mfgDate: "2026-07-01",
    expiryDate: "2026-11-01",
    image: "",
    packageSize: "50g Pouch",
    weight: "50g",
    manufacturer: "PepsiCo India Holdings Pvt Ltd",
    description: "Crispy ridged potato chips seasoned with Indian spices.",
    source: "database",
  },
  {
    name: "Lay's American Style Cream & Onion Chips",
    sku: "SKU-LAYS-CREAMONION-50G",
    barcode: "8901491101845",
    category: "Packaged Foods",
    brand: "Lay's",
    batch: "BATCH-LAYS-CO",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse B — Pune",
    shelf: "C2-02",
    minStock: 25,
    maxStock: 500,
    unit: "pcs",
    mfgDate: "2026-07-01",
    expiryDate: "2026-11-01",
    image: "",
    packageSize: "50g Pouch",
    weight: "50g",
    manufacturer: "PepsiCo India Holdings Pvt Ltd",
    description: "Thin sliced potato chips with creamy onion flavour.",
    source: "database",
  },
  {
    name: "Kurkure Masala Munch",
    sku: "SKU-KURKURE-90G",
    barcode: "8901491501010",
    category: "Packaged Foods",
    brand: "Kurkure",
    batch: "BATCH-KURK-1",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "C2-05",
    minStock: 30,
    maxStock: 600,
    unit: "pcs",
    mfgDate: "2026-07-01",
    expiryDate: "2026-11-01",
    image: "",
    packageSize: "90g Pouch",
    weight: "90g",
    manufacturer: "PepsiCo India Holdings Pvt Ltd",
    description: "Crunchy corn puffs seasoned with chatpata Indian spices.",
    source: "database",
  },
  {
    name: "Haldiram's Nagpur Aloo Bhujia",
    sku: "SKU-HALDIRAM-ALOO-200G",
    barcode: "8904063200018",
    category: "Packaged Foods",
    brand: "Haldiram's",
    batch: "BATCH-HALD-AB",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse D — Delhi NCR",
    shelf: "C3-01",
    minStock: 20,
    maxStock: 400,
    unit: "pcs",
    mfgDate: "2026-06-10",
    expiryDate: "2026-12-10",
    image: "",
    packageSize: "200g Pouch",
    weight: "200g",
    manufacturer: "Haldiram Foods International Pvt Ltd",
    description: "Spicy potato and chickpea flour noodle snacks.",
    source: "database",
  },
  {
    name: "Amul Pasteurised Butter 100g",
    sku: "SKU-AMUL-BUTTER-100G",
    barcode: "8901262010052",
    category: "Dairy & Chilled",
    brand: "Amul",
    batch: "BATCH-AMUL-B100",
    supplier: "Amul Distribution Co.",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "D1-01",
    minStock: 30,
    maxStock: 600,
    unit: "pcs",
    mfgDate: "2026-07-01",
    expiryDate: "2027-01-01",
    image: "",
    packageSize: "100g Carton",
    weight: "100g",
    manufacturer: "Gujarat Cooperative Milk Marketing Federation Ltd",
    description: "Utterly butterly delicious pure salted cream butter.",
    source: "database",
  },
  {
    name: "Amul Pasteurised Butter 500g",
    sku: "SKU-AMUL-BUTTER-500G",
    barcode: "8901262010069",
    category: "Dairy & Chilled",
    brand: "Amul",
    batch: "BATCH-AMUL-B500",
    supplier: "Amul Distribution Co.",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "D1-02",
    minStock: 20,
    maxStock: 400,
    unit: "pcs",
    mfgDate: "2026-07-01",
    expiryDate: "2027-01-01",
    image: "",
    packageSize: "500g Carton",
    weight: "500g",
    manufacturer: "Gujarat Cooperative Milk Marketing Federation Ltd",
    description: "500g block of pure rich salted dairy butter.",
    source: "database",
  },
  {
    name: "Amul Taaza Homogenised Toned Milk 1L",
    sku: "SKU-AMUL-TAAZA-1L",
    barcode: "8901262020013",
    category: "Dairy & Chilled",
    brand: "Amul",
    batch: "BATCH-AMUL-TZ1",
    supplier: "Amul Distribution Co.",
    warehouse: "Warehouse B — Pune",
    shelf: "D1-08",
    minStock: 40,
    maxStock: 800,
    unit: "tetra",
    mfgDate: "2026-07-01",
    expiryDate: "2026-10-01",
    image: "",
    packageSize: "1L Tetra Pak",
    weight: "1L",
    manufacturer: "Gujarat Cooperative Milk Marketing Federation Ltd",
    description: "UHT treated fresh toned milk with 3.0% fat, no preservatives.",
    source: "database",
  },
  {
    name: "Aashirvaad Superior MP Whole Wheat Atta 5kg",
    sku: "SKU-AASHIRVAAD-ATTA-5KG",
    barcode: "8901725131011",
    category: "Packaged Foods",
    brand: "Aashirvaad",
    batch: "BATCH-AASH-5K",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "E1-01",
    minStock: 15,
    maxStock: 300,
    unit: "bag",
    mfgDate: "2026-06-15",
    expiryDate: "2026-12-15",
    image: "",
    packageSize: "5kg Bag",
    weight: "5kg",
    manufacturer: "ITC Ltd",
    description: "100% pure whole wheat flour processed with traditional chakki grinding.",
    source: "database",
  },
  {
    name: "Tata Salt Vacuum Evaporated Iodised Salt 1kg",
    sku: "SKU-TATA-SALT-1KG",
    barcode: "8901030000025",
    category: "Packaged Foods",
    brand: "Tata",
    batch: "BATCH-TATA-S1",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "E1-05",
    minStock: 40,
    maxStock: 800,
    unit: "bag",
    mfgDate: "2026-05-01",
    expiryDate: "2028-05-01",
    image: "",
    packageSize: "1kg Bag",
    weight: "1kg",
    manufacturer: "Tata Consumer Products Ltd",
    description: "Desh Ka Namak — pure vacuum evaporated iodized table salt.",
    source: "database",
  },
  {
    name: "Fortune Sunlite Refined Sunflower Oil 1L",
    sku: "SKU-FORTUNE-OIL-1L",
    barcode: "8906007280014",
    category: "Packaged Foods",
    brand: "Fortune",
    batch: "BATCH-FORT-1L",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "E2-02",
    minStock: 30,
    maxStock: 600,
    unit: "pouch",
    mfgDate: "2026-06-01",
    expiryDate: "2027-03-01",
    image: "",
    packageSize: "1L Pouch",
    weight: "1L",
    manufacturer: "Adani Wilmar Ltd",
    description: "Light and healthy cooking oil enriched with vitamins A & D.",
    source: "database",
  },
  {
    name: "Surf Excel Easy Wash Detergent Powder 1kg",
    sku: "SKU-SURFEXCEL-1KG",
    barcode: "8901030020016",
    category: "Household",
    brand: "Surf Excel",
    batch: "BATCH-SURF-1K",
    supplier: "Reckitt Home Essentials",
    warehouse: "Warehouse B — Pune",
    shelf: "F1-01",
    minStock: 20,
    maxStock: 500,
    unit: "bag",
    mfgDate: "2026-06-01",
    expiryDate: "2028-06-01",
    image: "",
    packageSize: "1kg Bag",
    weight: "1kg",
    manufacturer: "Hindustan Unilever Ltd",
    description: "Tough stain removal powder suitable for bucket and machine wash.",
    source: "database",
  },
  {
    name: "Dettol Original Antiseptic Liquid 250ml",
    sku: "SKU-DETTOL-LIQUID-250ML",
    barcode: "8901396001015",
    category: "Pharmaceuticals",
    brand: "Dettol",
    batch: "BATCH-DET-250",
    supplier: "Reckitt Home Essentials",
    warehouse: "Warehouse C — Chennai",
    shelf: "F2-01",
    minStock: 15,
    maxStock: 300,
    unit: "bottle",
    mfgDate: "2026-05-10",
    expiryDate: "2028-05-10",
    image: "",
    packageSize: "250ml Bottle",
    weight: "250ml",
    manufacturer: "Reckitt Benckiser India Pvt Ltd",
    description: "Trusted first-aid disinfectant liquid for cuts, wounds, and hygiene.",
    source: "database",
  },
  {
    name: "Colgate Strong Teeth Anticavity Toothpaste 150g",
    sku: "SKU-COLGATE-150G",
    barcode: "8901314010518",
    category: "Personal Care",
    brand: "Colgate",
    batch: "BATCH-COLG-150",
    supplier: "Reckitt Home Essentials",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "F2-05",
    minStock: 25,
    maxStock: 500,
    unit: "tube",
    mfgDate: "2026-06-01",
    expiryDate: "2028-06-01",
    image: "",
    packageSize: "150g Tube",
    weight: "150g",
    manufacturer: "Colgate-Palmolive India Ltd",
    description: "Calcium and fluoride toothpaste that strengthens tooth enamel.",
    source: "database",
  },
  {
    name: "Nescafe Classic 100% Pure Instant Coffee 50g",
    sku: "SKU-NESCAFE-50G",
    barcode: "8901058000412",
    category: "Beverages",
    brand: "Nescafe",
    batch: "BATCH-NES-50",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse A — Hyderabad",
    shelf: "G1-01",
    minStock: 20,
    maxStock: 400,
    unit: "jar",
    mfgDate: "2026-06-01",
    expiryDate: "2028-06-01",
    image: "",
    packageSize: "50g Glass Jar",
    weight: "50g",
    manufacturer: "Nestle India Ltd",
    description: "Rich aroma and distinctive full-bodied instant roasted coffee.",
    source: "database",
  },
  {
    name: "Frooti Fresh 'n' Juicy Mango Drink 250ml",
    sku: "SKU-FROOTI-250ML",
    barcode: "8901063001013",
    category: "Beverages",
    brand: "Frooti",
    batch: "BATCH-FR-250",
    supplier: "ITC Foods Supply",
    warehouse: "Warehouse B — Pune",
    shelf: "G1-05",
    minStock: 30,
    maxStock: 600,
    unit: "tetra",
    mfgDate: "2026-07-01",
    expiryDate: "2027-01-01",
    image: "",
    packageSize: "250ml Tetra Pak",
    weight: "250ml",
    manufacturer: "Parle Agro Pvt Ltd",
    description: "Refreshing mango beverage made from real mango pulp.",
    source: "database",
  },
  {
    name: "Moov Pain Relief Specialist Spray 50g",
    sku: "SKU-MOOV-SPRAY-50G",
    barcode: "8901396340015",
    category: "Pharmaceuticals",
    brand: "Moov",
    batch: "BATCH-MOOV-50",
    supplier: "Reckitt Home Essentials",
    warehouse: "Warehouse C — Chennai",
    shelf: "H1-02",
    minStock: 15,
    maxStock: 300,
    unit: "spray",
    mfgDate: "2026-06-15",
    expiryDate: "2028-06-15",
    image: "",
    packageSize: "50g Aerosol Can",
    weight: "50g",
    manufacturer: "Reckitt Benckiser India Pvt Ltd",
    description: "Fast-acting pain relief spray with 100% natural Ayurvedic actives.",
    source: "database",
  },
];
